### ISSUE TITLE
Unfavorable password practices

### ISSUE THREAD

**Issue by brooke-ec** [Nathcat/data.nathcat.net#4]
Currently passwords are [stored using just SHA256](https://github.com/Nathcat/data.nathcat.net/blob/761201f332d8e77dae6f4e6d0c835721a61b3f08/sso/try-login.php#L51)- ideally you should use the [password_hash](https://www.php.net/manual/en/function.password-hash.php) function as SHA256 is not recommended for encryption in 2024. The current system is also vulnerable to [rainbow tables](https://en.wikipedia.org/wiki/Rainbow_table) and other similar attacks as there is no salt used. When logging in, the password should be compared using the [password_verify](https://www.php.net/manual/en/function.password-verify.php) function for simplicity and to avoid being vulnerable to [timing attacks](https://en.wikipedia.org/wiki/Timing_attack).

It is also inadvisable to allow passwords to be [pre-hashed on the client](https://github.com/Nathcat/data.nathcat.net/blob/761201f332d8e77dae6f4e6d0c835721a61b3f08/sso/try-login.php#L47) as then [the hash essentially *becomes* the password](https://security.stackexchange.com/a/8600) and you are back to storing passwords in plaintext. Granted, without leaking your users' actual passwords.

I am aware that these changes break the way that PeopleCat currently authenticates using your session. This could be remedied by sending the `AuthCat-SSO` cookie to the PeopleCat server, which can then check its validity with the AuthCat server.

### Step 1
![Authentication Diagram Step 1](https://github.com/user-attachments/assets/c5623558-83b4-40ae-aa75-770759dfc6bd)
This step can be skipped if the `AuthCat-SSO` session cookie has already been logged in with.

### Step 2
![Authentication Diagram Step 2](https://github.com/user-attachments/assets/bce39cfc-7222-47d4-bb83-50055134fc5f)

**Comment by ghostdevv** [comment]
> SHA256 is not recommended for encryption in 2024.

sha256 has never been good for password hashing. It's designed as a general purpose integrity check etc algorithm. A password hashing needs to be computationally taxing such that, you can't brute force it. It also needs to be salted which the implementations will handle for you.

Also to be pedantic it's not encryption, it's hashing. We hash passwords so that in the event of a leak, or something just looking at the data, they can't get the original password only the hash. This means that it's significantly harder in the event of a leak to get access to an account, as you first need to crack the password. Also protecting against the vast majority of people who use the same password. Salting also comes into play to ensure that two hashes of the same password are different.

I'd highly recommend reading this: https://thecopenhagenbook.com/password-authentication

**Comment by Nathcat** [comment]
Thank you guys, I will implement your suggestions in the branch attached to this issue.

**Comment by Nathcat** [comment]
> You may also have to have to have the current system as a fallback for a bit, until you have a chance to re-hash everyone's passwords with the new function.

I'll come up with some transition program for it. Allow existing users to login normally but then ask them to change their password before continuing, something like that.

**Comment by Nathcat** [comment]
Also implemented `cookie-auth` option in the PeopleCat server authentication request.
